using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class PlayerManager : MonoBehaviour
{
    // Variables
    private InputActions inputs;    // Inputs script class auto generated by the UI thingy in unity
    public InputActions.PlayerActions player;   // The inputs map for the player

    private PlayerMovement movement;

    private void Awake()
    {
        inputs = new InputActions();
        player = inputs.Player;

        movement = GetComponent<PlayerMovement>();
        

        // Jump is triggered
        player.Jump.performed += contex => movement.Jump();
        // Attack/Melee is triggered
        player.Melee.performed += contex => movement.Attack();
    }

    // Start is called before the first frame update
    void Start()
    {
        Cursor.visible = false;
        Cursor.lockState = CursorLockMode.Locked;
    }

    // Update is called once per frame
    void Update()
    {
        
    }

    // Fixed Update
    void FixedUpdate()
    {
        // When the player moves
        movement.ProcessMove(player.Move.ReadValue<Vector2>());
    }
    void LateUpdate()
    {

    }

    void OnEnable()
    {
        player.Enable();
    }

    void OnDisable()
    {
        player.Disable();
    }
}
